### ISSUE TITLE
Feature request: carouselTicker is NOT currently clickable on iPhone or iPad

### ISSUE THREAD

**Issue by inglesuniversal** [likeclever1/carouselTicker#12]
Hi Friend,

I was very excited with the looks of your project, until I stumbled with an unexpected issue.

I can touch or slide the carouselTicker on my iPhone or iPad.... BUT if I want to create <div onclick="playGame()" ... inside the line that displays each tiny square, it will NOT respond on my iPhone or iPad.

Is there a way to make the script more interactive so I can TRIGGER functions as I touch on any of the images that are scrolling?

Thans

**Comment by yuriyberezovskiy** [comment]
Hello, @inglesuniversal could you share your code or link with an example and I will try to help.

**Comment by inglesuniversal** [comment]
Thanks for your prompt reply...

Here is a DEMO link [TEST](https://mycloudvip-games.s3.amazonaws.com/test.html)

I love the script but somehow it won't work on iPhone or iPad when you tap on the tiny images.

Any clues or update needed to the script?

Take care friend

Regards

**Comment by yuriyberezovskiy** [comment]
Hm, it looks like a bug.

**Comment by inglesuniversal** [comment]
Do you think you can locate the bug? It would be greatly appreciated. 

Regards

**Comment by yuriyberezovskiy** [comment]
@inglesuniversal Fix was added and merged to the master branch.

**Comment by yuriyberezovskiy** [comment]
Fixed
