### ISSUE TITLE
Button to stop the carrousel

### ISSUE THREAD

**Issue by cpwom** [likeclever1/carouselTicker#15]
I'm trying to simply add a button to stop the carrousel (in order to make some kind of control panel) ... but can't make it stop scrolling. Is this totally wrong ?

`<button onclick="$('.carouselTicker').carouselTicker().stop();">stop</button>
`

Carrousel is working fine and started with : 
`    <script>
        $(document).ready(function() {
            $('.carouselTicker').carouselTicker({delay: 10});
        });
		
    </script>`

**Comment by yuriyberezovskiy** [comment]
It looks like you need to have variable
```
$(document).ready(function() {
  var $carousel = $('.carouselTicker').carouselTicker({delay: 10});
  
  $('.stopButton').on('click', function() {
    $carousel.stop();
  })
});
```
Button should have class `stopButton`
