### ISSUE TITLE
Change the direction

### ISSUE THREAD

**Issue by cpwom** [likeclever1/carouselTicker#18]
Hello Yuriy and thanks for the stop button help (works all fine) !

I wonder if it's possible to make buttons to change to direction of the carrousel, so people can click on them and it goes to the left or to the right ? As some people may not know them can drag/drop to do that ...

How should I implement them (I'm not a JS expert as you can see) ?

Regards
Cédric

**Comment by cpwom** [comment]
Hi, any chance you can lead me on how to do this ? I plan to use your carrousel on a website that will be used by accessibility disable people, so those buttons would help them.

thanks a lot.

**Comment by yuriyberezovskiy** [comment]
Hello @cpwom, currently this functionality is absent, so I need to extend the plugin by new logic.
I will do it when I will have free time, cause now I'm busy.
Let say - **2 weeks deadline** for this feature, hope it's ok for you.

**Comment by cpwom** [comment]
Hello, well this would be awesome ! Your plugin is really neat and clean, and I guess being able to put such actions (toleft, toright) on buttons would make it even better. I have several ideas where visitors would not think of sliding the scroller directly and would look for buttons to change the direction. I'm working on 2 sites where audience will be made of several kind of disabled people, and they would for sure appreciate that.

best regards and thanks for the always great support !!!
Cedric

**Comment by yuriyberezovskiy** [comment]
Hello, @cpwom I've added functionality for control carousel direction from buttons.

**Comment by cpwom** [comment]
Oh thanks a lot !!! I’ll check all this !

 

De : Yuriy ***@***.***> 
Envoyé : vendredi, 16 avril 2021 15:29
À : yuriyberezovskiy/carouselTicker ***@***.***>
Cc : cpwom ***@***.***>; Mention ***@***.***>
Objet : Re: [yuriyberezovskiy/carouselTicker] Change the direction (#18)

 

Hello, @cpwom <https://github.com/cpwom>  I've added functionality for control carousel direction from buttons.
