### ISSUE TITLE
Great script. can you update code to work with latest version of jQuery (e.g. 3.5.1?

### ISSUE THREAD

**Issue by inglesuniversal** [likeclever1/carouselTicker#9]
Also, is there a way to include a feature to force oposite direction when having multiple rows?

first --> scroll right
second ---> scroll left
third ---> scroll right
etc

[TEST](https://mycloudvip-games.s3.amazonaws.com/test.html)

IF I change jQuery to 3.5.1 I get this error inside the console

Uncaught TypeError: carouselTickerWidthResize.resizeTicker is not a function
    at start.js:36
    at dispatch (jquery.min.js:2)
    at v.handle (jquery.min.js:2)

Best regards and #STAYSAFE

**Comment by yuriyberezovskiy** [comment]
Hello @inglesuniversal, 
1) You can control the direction with the option `direction`.
2) It works well with the latest jQuery version, after updating I didn't notice any issues.

Probably your example has the wrong initialization.
If you want, for example, 3 carousels moving in different directions, and also been resizable, You need the next setup.

a) Keep 3 carousels on the page with different id, for example `#carouselTicker1`, `#carouselTicker2` and `#carouselTicker3`.
Then initialize them:

```
var carouselTicker1 = $("#carouselTicker1").carouselTicker();
var carouselTicker2 = $("#carouselTicker2").carouselTicker({ direction: next });
var carouselTicker3 = $("#carouselTicker3").carouselTicker();
```

And lastly, make them resizeable
```
$(window).on("resize", function () {
  carouselTicker1.resizeTicker();
  carouselTicker2.resizeTicker();
  carouselTicker3.resizeTicker();
});
```

Example
[example.zip](https://github.com/yuriyberezovskiy/carouselTicker/files/5638317/example.zip)
